### ISSUE TITLE
Error: SHA1 mismatch ...  To retry an incomplete download, remove the file above.

### ISSUE THREAD

**Issue by tiancovici** [totakke/homebrew-openni2#13]
> brew install openni2

==> Downloading https://github.com/occipital/OpenNI2/archive/2.2-beta2.tar.gz
Already downloaded: /Library/Caches/Homebrew/openni2-2.2.0.33.tar.gz
==> Downloading https://github.com/occipital/OpenNI2/pull/18.patch
###### ################################################################## 100.0%

Error: SHA1 mismatch
Expected: e0be30b6b9296939306155580df1ac7912d3f949
Actual: 4beb04a31a64677618801f0e95141807592442ef
Archive: /Library/Caches/Homebrew/openni2--patch-e0be30b6b9296939306155580df1ac7912d3f949.patch
To retry an incomplete download, remove the file above.

I've tried removing the file it told me to, but I end up at the same place. 
I did install openni prior to that, uninstalling then trying to install this didn't make a difference.

**Comment by IsFlwrs** [comment]
Hi I have the same problem when I tried to install elasticsearch

`brew install elasticsearch`
```
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.7.leopard_64.bottle.tar.gz
##########################


Error: Checksum mismatch.
Expected: 033ac518bb14abdb1bb47d968dc9e967c3ae2************************
Actual: bf51eede1e9c049d2165a45c7d0533b************************
Archive: /Users/********/Library/Caches/Homebrew/portable-ruby-2.3.7.leopard_64.bottle.tar.gz


To retry an incomplete download, remove the file above.
```

I solved the problem removing the `portable-ruby-2.3.7.leopard_64.bottle.tar.gz` file from my computer.

I used: 
`rm /Users/your-user/Library/Caches/Homebrew/portable-ruby-2.3.7.leopard_64.bottle.tar.gz`
